// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 619cda63c9146e64 "Mediso (copy)", do not edit manually */
'use client';

// virtual:service-card
import { Fragment as Fragment2, } from 'react';
import { ContextProviders, } from 'unframer';

// https :https://framerusercontent.com/modules/bgaiYfGxbWXNtDX40nSZ/Y4mSCd9JZ4Ty3FrFOqZk/FzJyyLkt1.js
import { jsx as _jsx, jsxs as _jsxs, } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext, } from 'unframer';
import * as React from 'react';

// https :https://framerusercontent.com/modules/dfpYjAbj377RtdHDCj0d/TXk50XAXvhz24VhJjq3c/O70TlKbcQ.js
import { fontStore, } from 'unframer';
fontStore.loadFonts(['FS;Satoshi-medium', 'FS;Satoshi-bold', 'FS;Satoshi-bold italic', 'FS;Satoshi-medium italic',],);
var fonts = [{
  explicitInter: true,
  fonts: [{
    family: 'Satoshi',
    source: 'fontshare',
    style: 'normal',
    url:
      'https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2',
    weight: '500',
  }, {
    family: 'Satoshi',
    source: 'fontshare',
    style: 'normal',
    url:
      'https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2',
    weight: '700',
  }, {
    family: 'Satoshi',
    source: 'fontshare',
    style: 'italic',
    url:
      'https://framerusercontent.com/third-party-assets/fontshare/wf/CDEBEFT2R7XKNGXSBBLZGMY4MMHZG75P/HEVKDGQCYDZ7Z6CDVR2ZQGBCTUD6ZARH/BKWEE3VKGTFABE37K2DTH625VUSN2N35.woff2',
    weight: '700',
  }, {
    family: 'Satoshi',
    source: 'fontshare',
    style: 'italic',
    url:
      'https://framerusercontent.com/third-party-assets/fontshare/wf/NID3I7RITWZSKXRCJGOCMP5NOADJK6IG/2HLHGD7OBTWCOHW64YXOE5KFXHU4KJHM/ZHME2QIRFR7UPJ47NLY27RCAFY44CKZJ.woff2',
    weight: '500',
  },],
},];
var css = [
  '.framer-80gmV .framer-styles-preset-yumnjo:not(.rich-text-wrapper), .framer-80gmV .framer-styles-preset-yumnjo.rich-text-wrapper h4 { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: #1f1f1f; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
  '@media (max-width: 1199px) and (min-width: 810px) { .framer-80gmV .framer-styles-preset-yumnjo:not(.rich-text-wrapper), .framer-80gmV .framer-styles-preset-yumnjo.rich-text-wrapper h4 { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 26px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: #1f1f1f; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
  '@media (max-width: 809px) and (min-width: 0px) { .framer-80gmV .framer-styles-preset-yumnjo:not(.rich-text-wrapper), .framer-80gmV .framer-styles-preset-yumnjo.rich-text-wrapper h4 { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: #1f1f1f; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className = 'framer-80gmV';

// https :https://framerusercontent.com/modules/lTmPz0i9bjUt6kybuzt2/qCAfHZf8bEY8XtH1nfmL/serTvl8yg.js
import { fontStore as fontStore2, } from 'unframer';
fontStore2.loadFonts(['FS;Satoshi-medium', 'FS;Satoshi-bold', 'FS;Satoshi-bold italic', 'FS;Satoshi-medium italic',],);
var fonts2 = [{
  explicitInter: true,
  fonts: [{
    family: 'Satoshi',
    source: 'fontshare',
    style: 'normal',
    url:
      'https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2',
    weight: '500',
  }, {
    family: 'Satoshi',
    source: 'fontshare',
    style: 'normal',
    url:
      'https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2',
    weight: '700',
  }, {
    family: 'Satoshi',
    source: 'fontshare',
    style: 'italic',
    url:
      'https://framerusercontent.com/third-party-assets/fontshare/wf/CDEBEFT2R7XKNGXSBBLZGMY4MMHZG75P/HEVKDGQCYDZ7Z6CDVR2ZQGBCTUD6ZARH/BKWEE3VKGTFABE37K2DTH625VUSN2N35.woff2',
    weight: '700',
  }, {
    family: 'Satoshi',
    source: 'fontshare',
    style: 'italic',
    url:
      'https://framerusercontent.com/third-party-assets/fontshare/wf/NID3I7RITWZSKXRCJGOCMP5NOADJK6IG/2HLHGD7OBTWCOHW64YXOE5KFXHU4KJHM/ZHME2QIRFR7UPJ47NLY27RCAFY44CKZJ.woff2',
    weight: '500',
  },],
},];
var css2 = [
  '.framer-Zsuj0 .framer-styles-preset-15c2nmh:not(.rich-text-wrapper), .framer-Zsuj0 .framer-styles-preset-15c2nmh.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.03em; --framer-line-height: 1.45em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-c7589b68-96fc-4f5c-b057-b4e9a66670e5, #787878); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
  '@media (max-width: 1199px) and (min-width: 810px) { .framer-Zsuj0 .framer-styles-preset-15c2nmh:not(.rich-text-wrapper), .framer-Zsuj0 .framer-styles-preset-15c2nmh.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.03em; --framer-line-height: 1.45em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-c7589b68-96fc-4f5c-b057-b4e9a66670e5, #787878); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
  '@media (max-width: 809px) and (min-width: 0px) { .framer-Zsuj0 .framer-styles-preset-15c2nmh:not(.rich-text-wrapper), .framer-Zsuj0 .framer-styles-preset-15c2nmh.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 19px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.03em; --framer-line-height: 1.45em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-c7589b68-96fc-4f5c-b057-b4e9a66670e5, #787878); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = 'framer-Zsuj0';

// https :https://framerusercontent.com/modules/bgaiYfGxbWXNtDX40nSZ/Y4mSCd9JZ4Ty3FrFOqZk/FzJyyLkt1.js
var cycleOrder = ['S96S3rF_z',];
var serializationHash = 'framer-EWX63';
var variantClassNames = { S96S3rF_z: 'framer-v-nzocq6', };
var transition1 = { damping: 60, delay: 0, mass: 1, stiffness: 500, type: 'spring', };
var toResponsiveImage = (value,) => {
  if (typeof value === 'object' && value !== null && typeof value.src === 'string') {
    return value;
  }
  return typeof value === 'string' ? { src: value, } : void 0;
};
var Transition = ({ value, children, },) => {
  const config = React.useContext(MotionConfigContext,);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition, }), [JSON.stringify(transition,),],);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children, },);
};
var Variants = motion(React.Fragment,);
var getProps = ({ heading, height, icon, id, link, text, width, ...props },) => {
  var _ref, _ref1, _ref2;
  return {
    ...props,
    DrfkTxnyP: (_ref = heading !== null && heading !== void 0 ? heading : props.DrfkTxnyP) !== null && _ref !== void 0
      ? _ref
      : 'Cardiology',
    F7Fm5RmDL: (_ref1 = text !== null && text !== void 0 ? text : props.F7Fm5RmDL) !== null && _ref1 !== void 0
      ? _ref1
      : 'We analyze your business and market to develop strategies that help you succeed.',
    lEKOW8y3I: link !== null && link !== void 0 ? link : props.lEKOW8y3I,
    M3K6b8BUS: (_ref2 = icon !== null && icon !== void 0 ? icon : props.M3K6b8BUS) !== null && _ref2 !== void 0
      ? _ref2
      : { src: 'https://framerusercontent.com/images/GIJPxyriwWLwWsMBtcF0x8KMoTE.svg', },
  };
};
var createLayoutDependency = (props, variants,) => {
  if (props.layoutDependency) return variants.join('-',) + props.layoutDependency;
  return variants.join('-',);
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref,) {
  const { activeLocale, setLocale, } = useLocaleInfo();
  const { style, className: className3, layoutId, variant, M3K6b8BUS, DrfkTxnyP, F7Fm5RmDL, lEKOW8y3I, ...restProps } = getProps(props,);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({ cycleOrder, defaultVariant: 'S96S3rF_z', variant, variantClassNames, },);
  const layoutDependency = createLayoutDependency(props, variants,);
  const ref1 = React.useRef(null,);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [className, className2,];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /* @__PURE__ */ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /* @__PURE__ */ _jsx(Transition, {
        value: transition1,
        children: /* @__PURE__ */ _jsx(Link, {
          href: lEKOW8y3I,
          children: /* @__PURE__ */ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(serializationHash, ...sharedStyleClassNames, 'framer-nzocq6', className3, classNames,)} framer-1suk7l8`,
            'data-border': true,
            'data-framer-name': 'Variant 1',
            layoutDependency,
            layoutId: 'S96S3rF_z',
            ref: ref !== null && ref !== void 0 ? ref : ref1,
            style: {
              '--border-bottom-width': '1px',
              '--border-color': 'var(--token-91ed012f-f7af-47e1-95e5-e1c97ec16b7c, rgba(33, 69, 62, 0.15))',
              '--border-left-width': '1px',
              '--border-right-width': '1px',
              '--border-style': 'solid',
              '--border-top-width': '1px',
              borderBottomLeftRadius: 26,
              borderBottomRightRadius: 26,
              borderTopLeftRadius: 26,
              borderTopRightRadius: 26,
              ...style,
            },
            children: [
              /* @__PURE__ */ _jsx(motion.div, {
                className: 'framer-1s9wusp',
                'data-framer-name': 'Icon Wrapper',
                layoutDependency,
                layoutId: 'gp4xM3j8N',
                style: {
                  backgroundColor: 'var(--token-e3493f1d-9011-4d8c-b7c2-f9da011acde2, rgb(250, 250, 250))',
                  borderBottomLeftRadius: 14,
                  borderBottomRightRadius: 14,
                  borderTopLeftRadius: 14,
                  borderTopRightRadius: 14,
                },
                children: /* @__PURE__ */ _jsx(Image, {
                  background: {
                    alt: '',
                    fit: 'fit',
                    loading: getLoadingLazyAtYPosition(
                      ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 30 +
                        ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) || 306) - 60 -
                              309.9) / 2 + 0 + 0) +
                        12,
                    ),
                    pixelHeight: 800,
                    pixelWidth: 800,
                    sizes: '30px',
                    ...toResponsiveImage(M3K6b8BUS,),
                    ...{ positionX: 'center', positionY: 'center', },
                  },
                  className: 'framer-5l45ou',
                  'data-framer-name': 'Icon',
                  layoutDependency,
                  layoutId: 'FTuX0bk7e',
                },),
              },),
              /* @__PURE__ */ _jsxs(motion.div, {
                className: 'framer-lm54se',
                'data-framer-name': 'Heading Wrap',
                layoutDependency,
                layoutId: 'wmEn3nxnq',
                children: [
                  /* @__PURE__ */ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /* @__PURE__ */ _jsx(React.Fragment, {
                      children: /* @__PURE__ */ _jsx(motion.h4, {
                        className: 'framer-styles-preset-yumnjo',
                        'data-styles-preset': 'O70TlKbcQ',
                        children: 'Cardiology',
                      },),
                    },),
                    className: 'framer-xfju1y',
                    fonts: ['Inter',],
                    layoutDependency,
                    layoutId: 'DoRqEKZ4E',
                    style: { '--framer-link-text-color': 'rgb(0, 153, 255)', '--framer-link-text-decoration': 'underline', },
                    text: DrfkTxnyP,
                    verticalAlignment: 'top',
                    withExternalLayout: true,
                  },),
                  /* @__PURE__ */ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /* @__PURE__ */ _jsx(React.Fragment, {
                      children: /* @__PURE__ */ _jsx(motion.p, {
                        className: 'framer-styles-preset-15c2nmh',
                        'data-styles-preset': 'serTvl8yg',
                        children: 'We analyze your business and market to develop strategies that help you succeed.',
                      },),
                    },),
                    className: 'framer-cm2ul7',
                    fonts: ['Inter',],
                    layoutDependency,
                    layoutId: 'KhcyK2u7x',
                    style: { '--framer-link-text-color': 'rgb(0, 153, 255)', '--framer-link-text-decoration': 'underline', },
                    text: F7Fm5RmDL,
                    verticalAlignment: 'top',
                    withExternalLayout: true,
                  },),
                ],
              },),
            ],
          },),
        },),
      },),
    },),
  },);
},);
var css3 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-EWX63.framer-1suk7l8, .framer-EWX63 .framer-1suk7l8 { display: block; }',
  '.framer-EWX63.framer-nzocq6 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 30px; position: relative; text-decoration: none; width: 367px; will-change: var(--framer-will-change-override, transform); }',
  '.framer-EWX63 .framer-1s9wusp { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 54px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 54px; will-change: var(--framer-will-change-override, transform); }',
  '.framer-EWX63 .framer-5l45ou { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 30px); overflow: hidden; position: relative; width: 30px; }',
  '.framer-EWX63 .framer-lm54se { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }',
  '.framer-EWX63 .framer-xfju1y, .framer-EWX63 .framer-cm2ul7 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-EWX63.framer-nzocq6, .framer-EWX63 .framer-1s9wusp, .framer-EWX63 .framer-lm54se { gap: 0px; } .framer-EWX63.framer-nzocq6 > * { margin: 0px; margin-bottom: calc(48px / 2); margin-top: calc(48px / 2); } .framer-EWX63.framer-nzocq6 > :first-child, .framer-EWX63 .framer-lm54se > :first-child { margin-top: 0px; } .framer-EWX63.framer-nzocq6 > :last-child, .framer-EWX63 .framer-lm54se > :last-child { margin-bottom: 0px; } .framer-EWX63 .framer-1s9wusp > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-EWX63 .framer-1s9wusp > :first-child { margin-left: 0px; } .framer-EWX63 .framer-1s9wusp > :last-child { margin-right: 0px; } .framer-EWX63 .framer-lm54se > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } }',
  ...css,
  ...css2,
  '.framer-EWX63[data-border="true"]::after, .framer-EWX63 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerFzJyyLkt1 = withCSS(Component, css3, 'framer-EWX63',);
var stdin_default = FramerFzJyyLkt1;
FramerFzJyyLkt1.displayName = 'Service card';
FramerFzJyyLkt1.defaultProps = { height: 306, width: 367, };
addPropertyControls(FramerFzJyyLkt1, {
  M3K6b8BUS: {
    __defaultAssetReference:
      'data:framer/asset-reference,GIJPxyriwWLwWsMBtcF0x8KMoTE.svg?originalFilename=bolt-svgrepo-com+%284%29.svg&preferredSize=auto',
    title: 'Icon',
    type: ControlType.ResponsiveImage,
  },
  DrfkTxnyP: { defaultValue: 'Cardiology', displayTextArea: false, placeholder: '', title: 'Heading', type: ControlType.String, },
  F7Fm5RmDL: {
    defaultValue: 'We analyze your business and market to develop strategies that help you succeed.',
    displayTextArea: true,
    title: 'Text',
    type: ControlType.String,
  },
  lEKOW8y3I: { title: 'Link', type: ControlType.Link, },
},);
addFonts(FramerFzJyyLkt1, [
  {
    explicitInter: true,
    fonts: [{
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
      url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
      url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+1F00-1FFF',
      url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0370-03FF',
      url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
      url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange:
        'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
      url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
      url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
      weight: '400',
    },],
  },
  ...getFontsFromSharedStyle(fonts,),
  ...getFontsFromSharedStyle(fonts2,),
], { supportsExplicitInterCodegen: true, },);

// virtual:service-card
import { WithFramerBreakpoints, } from 'unframer';
import { jsx, } from 'react/jsx-runtime';
var locales = [];
stdin_default.Responsive = ({ locale, ...props },) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routeId: 'x',
      routes: {
        x: {
          elements: {},
          page: /* @__PURE__ */ jsx(
            WithFramerBreakpoints,
            {
              Component: stdin_default,
              ...props,
            },
          ),
          path: '/',
        },
      },
      framerSiteId: '619cda63c9146e64e80cbcf8b1daadfbaa08bf8f7699d7ee73b0433430442f1d',
      locale,
      locales,
    },
  );
};
function ComponentWithRoot({ locale, ...rest },) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routeId: 'x',
      routes: {
        x: {
          elements: {},
          page: /* @__PURE__ */ jsx(stdin_default, { ...rest, },),
          path: '/',
        },
      },
      framerSiteId: '619cda63c9146e64e80cbcf8b1daadfbaa08bf8f7699d7ee73b0433430442f1d',
      locale,
      locales,
    },
  );
}
Object.assign(ComponentWithRoot, stdin_default,);
export { ComponentWithRoot as default, };
